version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    mem_reservation: 256m
    logging:
      driver: none
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=mindtree
      - POSTGRES_USER=me
      - POSTGRES_PASSWORD=password
      - PGDATA=/data/db
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
